### ISSUE TITLE
Launchpad page

### ISSUE THREAD

**Issue by AsifShaikh01** [ramNgithub/amazon.in-Clone#3]
### Task List (Day-4)
- [x] **Basic Structure of page**
- [x] **Styling of page**
- [x] **Fetching and showing products on page**
